name: asteroids
services:
- name: asteroids-server
  source_dir: asteroids-server
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: yarektyshchenko/asteroids
