name: asteroids
services:
- name: asteroids-server
  dockerfile_path: Dockerfile
  health_check:
    http_path: /socket.io/
  github:
    branch: master
    deploy_on_push: true
    repo: yarektyshchenko/asteroids
